### ISSUE TITLE
EF.Functions.Like support 

### ISSUE THREAD

**Issue by yoramda** [Eastrall/EntityFrameworkCore.DataEncryption#13]
Is there support for doing LIKE on encrypted fields?

EF.Functions.Like

for example 
var x = await _context.Contact.Where(x => EF.Functions.Like(x.FirstName, "jon%")).ToListAsync();

**Comment by Eastrall** [comment]
I don't know how work the `EF.Functions.Like` library, but I believe that it should work with encrypted fields since the `EntityFrameworkCore.DataEncryption` decrypts the fields before querying.

**Comment by alirazazulfi** [comment]
HI when we can have this feature built in to your library. i m facing the issue when i apply the Like with % or contains. if you can solve this using Contains then it will also be very great

**Comment by Gibrid89** [comment]
I have same problem. It's can be fixed?

**Comment by planeteleven0** [comment]
I did CLR integration with same algorithm that is used in EF, and manually decrypted in strored proc. side , but CLR integration it need to be done in .net framework

**Comment by fundenys** [comment]
Bonjour,
je m'excuse si je déterre le sujet.
Est il possible de outrepasser les fonctions "like", order by?
Avant EF, je faisais cette requete:
select top 10 * from user where decrypt(name,key) like "Fun%" order by decrypt(name,key)

J'avais créé la fonction decrypt sur le serveur SQL.

J'avais une table de plusieurs million de données et ça fonctionnait bien.

PS:Traduit with tools
