### ISSUE TITLE
Unable to correctly decrypt even it has the same AES key and IV

### ISSUE THREAD

**Issue by egenita** [Eastrall/EntityFrameworkCore.DataEncryption#2]
Hi,
The decryption is not working properly when the data is being accessed in other system even it share the same encryption key and IV. Do you know why it is so?

Thanks

**Comment by Eastrall** [comment]
Hello,

Thank you for using `EntityFrameworkCore.DataEncryption`!
Sharing same encryption key and IV is not enough. You also need share the way you encrypt data. Meaning, having the correct [CipherMode](https://docs.microsoft.com/en-US/dotnet/api/system.security.cryptography.ciphermode?view=netcore-2.2) and [PaddingMode](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.paddingmode?view=netcore-2.2) on each sides.

Hope it helps.

**Comment by Eastrall** [comment]
Closing issue.
