### ISSUE TITLE
How to disable Decryption for specific cases

### ISSUE THREAD

**Issue by hasansahinnn** [Eastrall/EntityFrameworkCore.DataEncryption#20]
For example, when we want to get data without any action on encrypted data, it causes an unnecessary loss of performance. Is there any way we can prevent this?

**Comment by Eastrall** [comment]
Hello,

You can create a second database context without calling the `UseEncryptionProvider()` to access the raw encrypted data without any action.
You could do something like:

```csharp
public class RawDatabaseContext : DbContext
{
    public DbSet<...> MyTable { get; set; }
}

public class EncryptedDatabaseContext : RawDatabaseContext
{
     protected override void OnModelCreating(ModelBuilder modelBuilder)
     {
          builder.UseEncryptionProvider(...);
     }
}
```

**Comment by Eastrall** [comment]
Version 3.0.0 is now available on Nuget and should fix this issue if you use the "fixed IV" option: https://www.nuget.org/packages/EntityFrameworkCore.DataEncryption
