### ISSUE TITLE
Seed data is updated every time

### ISSUE THREAD

**Issue by firedeepan** [Eastrall/EntityFrameworkCore.DataEncryption#22]
I have some seed data for one of my encrypted entities. Basically one of the columns in the entity is encrypted. When I generate migrations, it generates UpdateData commands every time for the seed data even though there is no change in the seed data. It only happens for entities with Encrypted attributes. Highly appreciate your help.

**Comment by Dumidu** [comment]
I am facing the same issue. Any solution?

**Comment by Eastrall** [comment]
This is due to the new `AesProvider` that generate an IV for each encrypted data. This has been made for security and good pratices principles, but I think I am going to revert this **or** provider the old provider that allows to specify a static IV for the Aes encryption.

**Comment by firedeepan** [comment]
@Eastrall is there any temporary solution you can suggest till you fix it?

**Comment by Eastrall** [comment]
The best solution I can come up with right now, is to take the V1.1.0 [`AesProvider`](https://github.com/Eastrall/EntityFrameworkCore.DataEncryption/blob/773c72243427e62de05b9734f0535d97180cf19c/src/EntityFrameworkCore.DataEncryption/Providers/AesProvider.cs) where you can provide a fixed IV that will allow you to use the Entity Framework LINQ features.

**Comment by Eastrall** [comment]
For a long-term fix, you will have to wait for V3.0 that restores the fixed `InitializationVector` for the `AesProvider`. See PR #25

**Comment by Eastrall** [comment]
Version 3.0.0 is now available on Nuget and should fix this issue if you use the "fixed IV" option: https://www.nuget.org/packages/EntityFrameworkCore.DataEncryption
