### ISSUE TITLE
EF core 5.0

### ISSUE THREAD

**Issue by heggi** [Eastrall/EntityFrameworkCore.DataEncryption#29]
Is it compatible with EF Core 5.0?

**Comment by Eastrall** [comment]
Hello @heggi, the library actually targets `netstandard2.0` and must have Entity Framework Core >= 3.1.0. So theoritically, it should work with EF Core 5.
If you are facing issues with EF Core 5, please reopen a new issue.

Let me know if I can close this issue.

**Comment by heggi** [comment]
Try basic queries with EFCore 5.0. 
It's work without errors!
