### ISSUE TITLE
Not compatible with ef core 5

### ISSUE THREAD

**Issue by grinay** [Eastrall/EntityFrameworkCore.DataEncryption#30]
Hi Guys. Trying to use your lib in my project and found that it's not compatible with ef 5. 
The problem in the file "EncryptionMigrator" the reflection is finding the method by name but in EF 5 there is two methods with name "Set"

Can you change it to  

```
public static class EncryptionMigrator
    {
        private static readonly MethodInfo SetMethod =
            typeof(DbContext).GetMethods()
                .First(x => x.GetParameters().Length == 0 && x.Name == nameof(DbContext.Set));

```

**Comment by Eastrall** [comment]
Hello, sorry to come back to you that late. There is actually a PR on hold to add support for .NET 5 and .NET 6. This might solve your issue.

I'll notify you on this issue when the upgrade will be released.
