### ISSUE TITLE
Support EFCore 7.0

### ISSUE THREAD

**Issue by heggi** [Eastrall/EntityFrameworkCore.DataEncryption#42]
Any plans?

**Comment by Eastrall** [comment]
Yes, `EntityFrameworkCore.DataEncryption` will support .NET 7. Version 4 is currently under development and will add .NET 7 support.

**Comment by Joffers** [comment]
Hi, any update on this?

**Comment by Uli-Armbruster** [comment]
@Eastrall Would you release version 4 on NuGet?

**Comment by Eastrall** [comment]
Shipped in 4.0.0
