### ISSUE TITLE
Add Mark by Fluent Api

### ISSUE THREAD

**Issue by IamMartinPeek** [Eastrall/EntityFrameworkCore.DataEncryption#44]
Hey got a question, could you add an extension to the fluent api so we can mark columns to be encrypted with the fluent api? Like a IsEncrypted()-Extension or something. I got my Db Models in another Library and don´t want to add a Nuget package to that library as it should have no dependencies.

**Comment by Eastrall** [comment]
Hi, fluent API support will be added in version `4.0.0`. Check PR #45. 😄

**Comment by Eastrall** [comment]
Shipped in 4.0.0
