### ISSUE TITLE
Creating a DBModelBuilder

### ISSUE THREAD

**Issue by rock1686** [Eastrall/EntityFrameworkCore.DataEncryption#5]
@Eastrall  I am trying to extend it and use it inside DBModelBuilder of a base context in the similar way as we used in the ModelBuilder.  The purpose is to use it in an existing project, which is making use of the DBModelBuilder in place of ModelBuilder.  If I try to create DBModelBuilderExtension, I am still not able to use the **SetValueConverters** function as they are not available coz the model is not **IMutableModel** Any thoughts how can we extend it to use **SetValueConverter**?

**Comment by Eastrall** [comment]
Hi, I have been doing some research about this topic, and it seems that the `DbModelBuilder` is part of the `Entity Framework 6.X` version. This library has been developed to target Entity Framewrok **Core** 2.1 and above to use the `SetValueConverter` feature.

I have no plans for making an update for Entity Framework 6.
