### ISSUE TITLE
Support EFCore 8

### ISSUE THREAD

**Issue by c5racing** [Eastrall/EntityFrameworkCore.DataEncryption#60]
Now that EFCore 8 is RC, is there plans to support it.  It appears there may be an issue when calling .UseEncryption(_provider);

**Comment by Eastrall** [comment]
Yes, EF Core 8 support is planned once it will be released as GA.
What is the issue you have when calling `UseEncryption(_provider)` ?

**Comment by c5racing** [comment]
![image](https://github.com/Eastrall/EntityFrameworkCore.DataEncryption/assets/11325751/0d0d28f2-342f-4a0e-a5b0-77d972e54d2e)

**Comment by fastman61** [comment]
#61 Please review

**Comment by c5racing** [comment]
Thank You!

**Comment by BetulComak** [comment]
https://github.com/Eastrall/EntityFrameworkCore.DataEncryption/pull/61 Please review

**Comment by sezer** [comment]
@Eastrall can you check #61 is fixes it?

**Comment by Eastrall** [comment]
Thanks for the interest you are all porting to the library! I have seen the PR, I'll merge it later today and release the new version on NuGet at the same time.

**Comment by periapsistech** [comment]
@Eastrall can you add new release for the .NET 8 support?

**Comment by Eastrall** [comment]
Version 5.0.0 is now available on NuGet: https://www.nuget.org/packages/EntityFrameworkCore.DataEncryption/5.0.0
See full changelog here: https://github.com/Eastrall/EntityFrameworkCore.DataEncryption/releases/tag/v5.0.0

Thank you all for your patience, and thank you @fastman61 for the PR!
