### ISSUE TITLE
[Question] Migrating existing data

### ISSUE THREAD

**Issue by jbarczyk** [Eastrall/EntityFrameworkCore.DataEncryption#7]
Is there a good way to migrate existing data using this extension? 
Usecase: Database with data already existing and the data needs to be encrypted

**Comment by Eastrall** [comment]
Hi,

Unfortunately, the library doesn't support this use case. We can add this feature to the library's roadmap thought.

**Comment by jbarczyk** [comment]
Would be great, thanks!

**Comment by mguinness** [comment]
If you're using MySQL you can use the [AES_ENCRYPT()](https://dev.mysql.com/doc/refman/8.0/en/encryption-functions.html#function_aes-encrypt) function to encrypt existing data.

**Comment by Eastrall** [comment]
PR #25 has introduced a migration provider: https://github.com/Eastrall/EntityFrameworkCore.DataEncryption/releases/tag/v3.0.0
